### PR TITLE
Update neural_network.py to be able to load old model weights

### PR DESCRIPTION
**Pull request by wjguan**

### CODE REVIEW

**Comment by wjguan** [comment]
This pull request addresses Issues #51 and #41

**Comment by PolarBean** [comment]
Hey great job :)

Im testing it on my side and getting the following issue.
Is the example in the readme working on your machine?

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], [line 3](vscode-notebook-cell:?execution_count=1&line=3)
      [1](vscode-notebook-cell:?execution_count=1&line=1) from DeepSlice import DSModel
      [2](vscode-notebook-cell:?execution_count=1&line=2) species = 'mouse' 
----> [3](vscode-notebook-cell:?execution_count=1&line=3) Model = DSModel(species)

File [~/github/DeepSlice/DeepSlice/main.py:21](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/main.py:21), in DSModel.__init__(self, species)
     [19](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/main.py:19) xception_weights =   metadata_loader.get_data_path(self.config["weight_file_paths"]["xception_imagenet"], self.metadata_path)
     [20](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/main.py:20) weights =    metadata_loader.get_data_path(self.config["weight_file_paths"][self.species]["primary"], self.metadata_path)
---> [21](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/main.py:21) self.model = neural_network.initialise_network(xception_weights, weights, self.species)

File [~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:58](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:58), in initialise_network(xception_weights, weights, species)
     [55](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:55)     model.add(Dense(9, activation="linear"))
     [57](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:57) if weights != None:
---> [58](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:58)     model = load_xception_weights(model, weights)
     [59](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:59) return model

File [~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:65](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:65), in load_xception_weights(model, weights)
     [62](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:62) def load_xception_weights(model, weights):
     [63](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:63)     with h5py.File(weights, "r") as new:
     [64](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:64)         # set weight of each layer manually
---> [65](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:65)         model.layers[1].set_weights([new["dense"]["dense"]["kernel:0"], new["dense"]["dense"]["bias:0"]])
     [66](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:66)         model.layers[2].set_weights([new["dense_1"]["dense_1"]["kernel:0"], new["dense_1"]["dense_1"]["bias:0"]])
     [67](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/github/DeepSlice/DeepSlice/neural_network/neural_network.py:67)         model.layers[3].set_weights([new["dense_2"]["dense_2"]["kernel:0"], new["dense_2"]["dense_2"]["bias:0"]])

File [~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:666](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:666), in Layer.set_weights(self, weights)
    [664](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:664) layer_weights = self.weights
    [665](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:665) if len(layer_weights) != len(weights):
--> [666](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:666)     raise ValueError(
    [667](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:667)         f"You called `set_weights(weights)` on layer '{self.name}' "
    [668](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:668)         f"with a weight list of length {len(weights)}, but the layer "
    [669](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:669)         f"was expecting {len(layer_weights)} weights."
    [670](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:670)     )
    [671](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:671) for variable, value in zip(layer_weights, weights):
    [672](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/harryc/github/DeepSlice/~/anaconda3/lib/python3.11/site-packages/keras/src/layers/layer.py:672)     if variable.shape != value.shape:

ValueError: You called `set_weights(weights)` on layer 'dense' with a weight list of length 2, but the layer was expecting 0 weights.

```

**Comment by PolarBean** [comment]
Ok interesting, it works perfectly when I use tensorflow 2.13.1 but errors on 2.16.1. We can just pin tf to 2.13 for now.

**Comment by wjguan** [comment]
Cool, I updated the setup.py!

**Comment by PolarBean** [comment]
Looks good!

**Comment by wjguan** [comment]
OK, so I tested with tensorflow == 2.15.0 and it also worked. I guess 2.16 is where they made some big changes to the way that keras Models were structured

**Comment by PolarBean** [comment]
haha pretty typical, I think your solution is great. We can pin to <=2.15 and it will be ages before it becomes an issue.

**Pull request merged**
